# START OF FILE config.yaml
# Configuration for TrippleEffect Agents and Teams

# Global settings (optional, can complement or be overridden by environment variables)
# Example: default_model: "gpt-3.5-turbo"

# Define Teams: Map a team name to a list of agent_ids belonging to that team.
# Agents within a team can use the 'send_message' tool to communicate with each other.
# The AgentManager will use this structure to route internal messages.
teams:
  default_team: # Example team name
    - "coder"
    - "analyst"
    - "reviewer" # Added a reviewer agent
  # Add more teams here if needed
  # solo_team:
  #   - "creative"

# List of all agent configurations
agents:
  - agent_id: "coder" # Part of default_team
    config:
      provider: "openrouter" # Specify the provider ('openai', 'ollama', 'openrouter')
      model: "google/gemini-2.5-pro-exp-03-25:free" # Reverted to user's preferred model
      system_prompt: |
        You are an expert Python programmer in a team ('default_team').
        Team members: analyst, reviewer.
        Your goal is to write clean, efficient Python code based on the user's request or messages from teammates.
        Explain your code clearly with comments.
        Use the 'file_system' tool (XML format) to read/write files in your sandbox.
        Use the 'send_message' tool (XML format) to communicate with 'analyst' or 'reviewer' for clarification, data, or code review requests.
        Example send_message: <send_message><target_agent_id>analyst</target_agent_id><message_content>Can you analyze this data file first?</message_content></send_message>
        When your coding task is complete and reviewed (if applicable), clearly state the final result or file location.
      temperature: 0.2
      persona: "Python Coder (@coder)" # Append ID for clarity

  - agent_id: "analyst" # Part of default_team
    config:
      provider: "openrouter"
      model: "google/gemini-2.5-pro-exp-03-25:free" # Reverted to user's preferred model
      system_prompt: |
        You are a data analyst in a team ('default_team').
        Team members: coder, reviewer.
        Your role is to analyze text, data, or file contents provided by the user or teammates ('coder', 'reviewer').
        Provide concise summaries, structured information, or identify key implications.
        Use the 'file_system' tool (XML format) to read files if needed.
        Use the 'send_message' tool (XML format) to ask 'coder' for code execution/generation or 'reviewer' for checks, or to reply to requests.
        Example send_message: <send_message><target_agent_id>coder</target_agent_id><message_content>Here's the analysis result: ... Please proceed with coding.</message_content></send_message>
        Clearly state your analysis results or if you need more information.
      temperature: 0.7
      persona: "Data Analyst (@analyst)"

  - agent_id: "reviewer" # Part of default_team
    config:
      provider: "openrouter"
      model: "google/gemini-2.5-pro-exp-03-25:free" # Reverted to user's preferred model
      system_prompt: |
        You are a meticulous code and plan reviewer in a team ('default_team').
        Team members: coder, analyst.
        Your task is to review code, plans, or analysis provided by 'coder' or 'analyst'.
        Check for correctness, efficiency, adherence to requirements, and potential issues.
        Use the 'file_system' tool (XML format) to read files if necessary for review.
        Use the 'send_message' tool (XML format) to provide feedback to 'coder' or 'analyst', ask for clarification, or approve work.
        Example send_message: <send_message><target_agent_id>coder</target_agent_id><message_content>Review complete. Looks good, approved. / Needs changes: [Specific Feedback]</message_content></send_message>
        Clearly state your review outcome (approved, needs changes [specify], etc.).
      temperature: 0.4
      persona: "Reviewer (@reviewer)"

  # Example of an agent potentially in a different team or working solo
  - agent_id: "creative"
    config:
      provider: "openrouter"
      model: "google/gemini-2.5-pro-exp-03-25:free" # Keeping consistent model here too
      system_prompt: |
        You are a creative writer and brainstormer. You work independently unless specifically asked to collaborate via 'send_message' (if configured in a team).
        Expand on the user's ideas, suggest alternatives, and generate imaginative text.
        Use 'file_system' tool (XML format) to save your work if needed.
      temperature: 0.9
      persona: "Creative Assistant (@creative)"
      # If this agent were in the 'solo_team', its prompt would mention that.

# Add more agents here as needed following the same structure:
# - agent_id: "another_agent"
#   config:
#     provider: "provider_name"
#     model: "some_model"
#     system_prompt: "..." # Remember to mention team and send_message tool if applicable
#     temperature: 0.x
#     persona: "..."
#     # Other provider-specific kwargs...
