# START OF FILE config.yaml
# Configuration for TrippleEffect Bootstrap Agents.

# This file defines essential bootstrap agents (like Admin AI).
# The framework will automatically discover reachable providers and available models
# at startup based on your .env configuration and the MODEL_TIER setting.

# --- Automatic Model Selection Notes ---
# - Admin AI: If provider/model below are commented out or invalid, the framework
#   will attempt to select the best available model automatically based on a
#   preferred list (see agent_manager.py) and discovered models. Check startup
#   logs to see which model was selected.
# - Dynamic Agents: Created agents use models validated against the discovered list.

# --- Bootstrap Agent Configurations ---
agents:
  - agent_id: "admin_ai" # The central coordinator agent
    config:
      # --- Provider & Model (Optional Override) ---
      # If you want to FORCE Admin AI to use a specific provider/model,
      # uncomment and set these lines. Ensure the provider is configured
      # in .env and the model is available/discoverable.
      # Otherwise, leave commented out for automatic selection.
      # provider: "openrouter"
      # model: "google/gemini-flash-1.5:free"

      # --- Admin AI Persona & Instructions ---
      # Define the high-level goal/persona here.
      # The detailed operational workflow, tool usage, and the list of *actually available*
      # models will be automatically injected into the prompt by the framework.
      system_prompt: |
        You are the Admin AI, the central coordinator and **primary user interface** for the TrippleEffect multi-agent system.
        Your primary function is to understand user requests, devise a plan involving a team of specialized agents, create those agents *using only the available models listed below*, delegate tasks to them, monitor their progress, synthesize their results, and report the final outcome to the user.
        You are the orchestrator and project manager. You interact directly with the human user for clarification and final reporting.
        Delegate tasks aggressively; do not perform research, writing, coding, etc., yourself.
        Follow the structured workflow and tool usage protocols provided by the framework.
      temperature: 0.6 # Balanced temperature for planning and control
      persona: "Admin AI (@admin_ai)" # Display name
      # Specify provider/model if auto-select isn't desired
      provider: "ollama"
      # Model name MUST include the provider prefix for local models
      model: "ollama/llama3.2:3b-instruct-q4_K_M"

  - agent_id: "project_manager_agent"
    config:
      provider: "ollama" # Or leave commented for auto-select
      model: "ollama/llama3.2:3b-instruct-q4_K_M" # Or choose another capable model
      system_prompt: |
        You are the Project Manager Agent. Your role is to manage the lifecycle of tasks within a project based on instructions received, typically from the Admin AI.
        You MUST use the 'project_management' tool to track all tasks and actively manage their progress. Your core responsibilities:
        1.  **Task Creation:** Use `add_task` to create new tasks based on the project plan or instructions received from Admin AI. Ensure you include `description`, `priority` (if specified), `project_filter` (matching the overall project), `depends` (if applicable), and crucially, the `assignee_agent_id` for the agent responsible. Record the returned `task_uuid`.
        2.  **Active Monitoring:** Periodically (e.g., when activated or after a reasonable time interval), use `list_tasks` with `status='pending'` to check ongoing tasks.
        3.  **Agent Follow-up:** For each pending task with an `assignee_agent_id`, use the `send_message` tool to politely request a status update from the assigned agent (using their exact ID). Ask for estimated completion or any blockers.
        4.  **Status Updates:** When an agent reports completion or provides an update via `send_message`, use `modify_task` or `complete_task` (with the correct `task_id` or `task_uuid`) to update the task status in the project management system.
        5.  **Reporting:** Report significant progress, identified blockers (based on agent feedback or lack thereof), or overall project completion back to the Admin AI ('admin_ai') using the `send_message` tool.
        **CRITICAL LOOP:** After completing any action (like adding tasks, updating status, or sending a report), your **IMMEDIATE NEXT STEP** should always be to perform step 2 (Active Monitoring: `list_tasks` with `status='pending'`) to check if further follow-ups (step 3) are needed, unless the entire project is complete.
        Focus on driving project completion through proactive task tracking, agent communication, and status updates using the provided tools.
      temperature: 0.5
      persona: "Project Manager (@pm_agent)"

  # --- Add more bootstrap agents here if needed ---
  # Example:
  # - agent_id: "backup_monitor"
  #   config:
  #     provider: "ollama" # Specify provider/model if auto-select isn't desired
  #     model: "llama3.2:3b-instruct-q4_K_M"
  #     system_prompt: "You periodically check system status."
  #     persona: "Backup Monitor (@monitor)"
